services:
  postgres:
    container_name: postgres_keycloak
    image: postgres:15.3
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./keycloak-postgres.env
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_keycloak
    image: dpage/pgadmin4:7.5
    env_file:
      - ./keycloak-postgres.env
    ports:
      - "5050:80"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    restart: always
    command:
      - start-dev
    depends_on:
      - "postgres"
    env_file:
      - ./keycloak-postgres.env
    ports:
      - 8090:8080
      - 8787:8787 # debug port
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
